from enum import Enum


class IOCType(str, Enum):
    """Types of Indicators of Compromise (Extracted from JSON - real world would be pulled from somewhere else)"""

    APPLICATION_CRASH_LOG = "application_crash_log"
    APPLICATION_LOG_PATTERN = "application_log_pattern"
    AUTHENTICATION_LOG = "authentication_log"
    BROWSER_ALERT = "browser_alert"
    BROWSER_CONSOLE_ERROR = "browser_console_error"
    CLOUD_API_CALL = "cloud_api_call"
    COMMAND_LINE = "command_line"
    CONTAINER_ID = "container_id"
    DATABASE_QUERY_PATTERN = "database_query_pattern"
    DESTINATION = "destination"
    DNS_RECORD = "dns_record"
    FILE_EXTENSION = "file_extension"
    FILE_HASH = "file_hash"
    FILE_PATH = "file_path"
    HTTP_REQUEST_BODY = "http_request_body"
    HTTP_REQUEST_HEADER = "http_request_header"
    HTTP_REQUEST_PARAMETER = "http_request_parameter"
    HTTP_REQUEST_PATTERN = "http_request_pattern"
    HTTP_RESPONSE_BODY = "http_response_body"
    HTTP_RESPONSE_HEADER = "http_response_header"
    INPUT_DATA_PATTERN = "input_data_pattern"
    IP_ADDRESS = "ip_address"
    LIBRARY_NAME = "library_name"
    LIBRARY_VERSION = "library_version"
    MEMORY_ACCESS_PATTERN = "memory_access_pattern"
    NETWORK_CONNECTION = "network_connection"
    NETWORK_TRAFFIC_PATTERN = "network_traffic_pattern"
    NETWORK_TRAFFIC_VOLUME = "network_traffic_volume"
    PROCESS_BEHAVIOR = "process_behavior"
    PROCESS_NAME = "process_name"
    RESPONSE_SIZE = "response_size"
    SOURCE_IP = "source_ip"
    SYSCALL_PATTERN = "syscall_pattern"
    SYSTEM_CALL_SEQUENCE = "system_call_sequence"
    THREAT_INTEL_ALERT = "threat_intel_alert"
    TIMING_ANOMALY = "timing_anomaly"
    TRAFFIC_SOURCE_COUNT = "traffic_source_count"
    URI_PATH = "uri_path"
    URL = "url"
    USER_BEHAVIOR = "user_behavior"
    USER_INPUT_HISTORY = "user_input_history"
    USERNAME = "username"
    WAF_ALERT = "waf_alert"
    DOMAIN = "domain"
    EMAIL = "email"
    REGISTRY_KEY = "registry_key"
    CERTIFICATE = "certificate"
    USER_AGENT = "user_agent"
    MUTEX = "mutex"
    NETWORK_SIGNATURE = "network_signature"
    YARA_RULE = "yara_rule"
    OTHER = "other"
