# Incident Research User Prompt

RESEARCH_USER_PROMPT = """# Security Incident Research Request

## Incident Information:
**Incident ID**: {incident_id}
**Timestamp**: {timestamp}
**Title**: {title}
**Description**: {description}
**Initial Findings**: {initial_findings}

## Affected Assets:
{affected_assets_info}

## Observed TTPs:
{observed_ttps_info}

## Indicators of Compromise:
{indicators_info}

## Pre-processed Vulnerability Report:
{vulnerability_report}

**Important Note**: The pre-processed vulnerability report is a starting point generated by automated tools. It may contain false positives, miss relevant vulnerabilities, or lack important context. Your research should validate, expand upon, and contextualize these findings.

---

## Your Research Mission:

Conduct comprehensive research on this security incident to gather all relevant information needed for thorough analysis. Your research should be systematic, thorough, and focused on actionable intelligence.

## Research Objectives:

### 1. **Vulnerability Deep Dive**
- Research each software component mentioned in the incident
- Validate and expand the pre-processed vulnerability data
- Search for additional CVEs that might be relevant to the incident context
- Investigate version-specific vulnerabilities and their exploitation status

### 2. **Attack Pattern Research**
- Research the observed TTPs to understand attack methodologies
- Look for related attack campaigns or threat actor patterns
- Investigate how the identified vulnerabilities might support the observed attack progression
- Search for indicators of similar attacks or campaigns

### 3. **Threat Intelligence Collection**
- Gather intelligence on threat actors who use similar TTPs
- Research recent campaigns targeting similar software or organizations
- Investigate any indicators of compromise for additional context
- Look for attribution indicators or campaign connections

### 4. **Software Component Analysis**
- Research each affected software component for:
  - Known security issues beyond CVEs
  - Configuration vulnerabilities
  - Default credential issues
  - Update and patch status
  - End-of-life considerations

### 5. **Contextual Intelligence**
- Research environmental factors that might affect exploitation
- Investigate network exposure considerations
- Look for information about asset criticality and business impact
- Research detection and mitigation strategies

## Research Strategy Guidelines:

- **Start Broad, Then Focus**: Begin with general searches, then drill down into specific findings
- **Follow the Evidence**: Let interesting discoveries guide additional research directions
- **Cross-Validate**: Verify important findings across multiple sources
- **Document Methodology**: Keep track of your research approach and sources
- **Assess Confidence**: Evaluate the reliability and confidence level of each finding
- **Identify Gaps**: Note areas where research was limited or information was unavailable

## Research Quality Standards:

- **Relevance**: Focus on information directly applicable to this incident
- **Accuracy**: Ensure findings are properly sourced and verified
- **Completeness**: Aim for comprehensive coverage of all incident components
- **Timeliness**: Prioritize recent and current threat intelligence
- **Actionability**: Gather information that will support decision-making in the analysis phase

## Expected Research Outcomes:

Your research should produce:
- **Enhanced CVE Intelligence**: Detailed information about relevant vulnerabilities
- **Software Security Profiles**: Comprehensive security assessments of affected software
- **Threat Context**: Intelligence about threat actors, campaigns, and attack patterns
- **Environmental Factors**: Information about the incident environment and context
- **Research Documentation**: Clear methodology and source documentation
- **Gap Analysis**: Identification of research limitations and areas needing follow-up

## Submission Requirements:

When your research is complete, use the `submit_research` tool to provide:
- All CVE research findings with relevance assessments
- Software component research results
- Threat intelligence discoveries
- Research methodology and sources consulted
- Key discoveries and insights
- Identified research gaps and limitations
- Recommended next steps for the analysis stage

Remember: The analysis stage depends on the quality and comprehensiveness of your research. Be thorough, systematic, and document everything clearly.

Every answer must be in the form of a tool call. You should NEVER answer directly in the chat."""